config/routes.rb
Rails.application.routes.draw do
  get 'principal/home'
  get 'wordings/my'
  resources :wordings do
    resources :reviews
  end
  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'principal#home'
  match '*unmatched_route', to: "application#page_not_found", via: :all

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :wording

  validates :rate, presence: true, inclusion: { in: 0..1000 }

  def writer
  	return self.user.email
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :wordings
	has_many :reviews
	validates :name,
    length: {maximum: 200,
    message:" não pode ter mais do que 200 caracteres"}, 
    presence: {message:"em branco"}
	validates :lastname,length: {maximum: 200,
    message:" não pode ter mais do que 200 caracteres"}, 
    presence: {message:"em branco"}
  validates :encrypted_password, presence: true
  validates :email, email: true
	HUMANIZED_LASTNAME = {
    	lastname: "Sobrenome"
  	}
  	HUMANIZED_NAME = {
    	name: "Nome"
  	}
  	HUMANIZED_PASS = {
    	password: "Senha"
  	}
  	def self.human_attribute_name(attr, options = {})
    	HUMANIZED_LASTNAME[attr.to_sym] || 
    	 	HUMANIZED_NAME[attr.to_sym] || 
    	 	HUMANIZED_PASS[attr.to_sym] || super
  	end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wording.rb
class Wording < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  validates :title, length: {maximum: 200, message:" não pode ter mais do que 200 caracteres"}
  validates :text, presence: {message: "não pode ser em branco"}
  HUMANIZED_TEXT = {
      text: "O texto"
  }
  HUMANIZED_TITLE = {
      text: "O texto"
  }
  def self.human_attribute_name(attr, options = {})
      HUMANIZED_TEXT[attr.to_sym] || super
    end
  def score
    @score = 0;
    if self.reviews.count == 0
      @score = 0
    else
      self.reviews.each do |r|
        if(r.valid?)
          @score += r.rate
        end
      end
      @score /= self.reviews.count
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_filter :authenticate_user!
def page_not_found
    render plain: "404 Not Found", status: 404
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def home
  	@bests_wordings = Wording.all.sort {|left, right| right.score <=> left.score}
  	@bests_wordings = @bests_wordings.take(3)
  	if !user_signed_in?
  		redirect_to user_session_path
  	end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	






	before_filter :configure_devise_permitted_parameters, if: :devise_controller?

	  protected

	  def configure_devise_permitted_parameters
	    permitted_params = [:name, :lastname, :email, :password, :password_confirmation]

	    if params[:action] == 'update'
	      devise_parameter_sanitizer.for(:account_update) { 
	        |u| u.permit(permitted_params << :current_password)
	      }
	    elsif params[:action] == 'create'
	      devise_parameter_sanitizer.for(:sign_up) { 
	        |u| u.permit(permitted_params) 
	      }
	    end
	  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		@wording = Wording.find(params[:wording_id])
		@review = @wording.reviews.create(review_params)
		@review.user = current_user

		if @review.save
			redirect_to @wording
		else
    		flash[:notice] = "Comentário invalido"
    		render "wordings/show"
    	end
    	
	end
	def destroy
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to :back
	end
	private
	def review_params
		params.require(:review).permit(:rate,:comment)
	end
end

app/controllers/wordings_controller.rb
class WordingsController < ApplicationController
	def new 
		@wording = Wording.new
	end 
	def my
		@wordings = current_user.wordings
	end
	def create
		@wording = Wording.new(post_params)
		@wording.user = current_user
		if @wording.save
            redirect_to @wording
        else
            render 'new'
        end
	end
	def index
		@wordings = Wording.all
	end
	def show
		flash[:notice] = ""
		@wording = Wording.find(params[:id])
	end

	def destroy
		@wording = Wording.find(params[:id])
		@wording.reviews.destroy
		@wording.destroy
		redirect_to :back
	end
	private
	def post_params
		params.require(:wording).permit(:title,:text)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/wordings_helper.rb
module WordingsHelper
end

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/_user_signin.erb
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to principal_home_path do %>
            <span class="navbar-brand">Escriba</span>
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%=link_to "Perfil", edit_user_registration_path%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Redações <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Nova Redação', new_wording_path%></li>
                <li><%= link_to 'Minhas Redações', wordings_my_path%></li>
                <li><%= link_to 'Todas Redações', wordings_path%></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-power-off"></i>
            <% end %>
          </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Escriba</title>
    <link href="navbar-static-top.css" rel="stylesheet">
    <link href="signin.css" rel="stylesheet">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
      <% if user_signed_in? %>
        <%= render 'layouts/user_signin' %>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/principal/home.html.erb
<div class="container">
	<div class="jumbotron">
	    <h1>Bem-vindo!</h1>
	    <!--<% current_user.wordings.each do |wording| %>
	    	<%= wording.title %>
	    	<%= wording.text %>
	    <% end %>-->

	    <h4>Além de criar suas redações, aqui você pode comentar e avaliar de outros usuarios.</h4>
	</div>
		<h1>Melhores redações</h1>
	    <div class="row">
	      <% @bests_wordings.each do |wording| %>
	      	<% if wording.valid? %>
		        <div class="col-md-4">
		          <h2><%=wording.score%></h2>
		          <h3><%=wording.title.at(0..20)%></h3>
		          <p style="word-wrap: break-word"><%=wording.text.at(0..200)+"..."%> </p>
		          <%= button_to 'Detalhes', wording_path(wording), method: :get, class:'btn btn-default' %>
		        </div>
	      	<%end%>
		<%end%>
	</div>
	
</div>

app/views/wordings/index.html.erb
<div class="container">
	<div class="row">
	      <% @wordings.each do |wording| %>
	      	<% if wording.valid? %>
	      		<div class="col-md-4">
					<div class="panel panel-default">
					  	<div class="panel-body">
					  	  <h2><%=wording.score%></h2>
				          <h3><%=wording.title.at(0..20)%></h3>
				          <p style="word-wrap: break-word"><%=wording.text.at(0..200)+"..."%> </p>
				          <%= button_to 'Detalhes', wording_path(wording), method: :get, class:'btn btn-default' %>
				    	</div>
					</div>
				</div>
		        
	      	<%end%>
		<%end%>
	</div>
</div>

app/views/wordings/my.html.erb
<div class="container">
	<div class="row">
	      <% @wordings.each do |wording| %>
	      	<% if wording.valid? %>
	      		<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading">
							<%= link_to wording_path(wording),  method: :delete, data: { confirm: 'Tem certeza?' } do %>
            					<i class="fa fa-times"></i>
          					<% end %>
							
						</div>
					  	<div class="panel-body">
				          <h2><%=wording.title.at(0..20)%></h2>
				          <p style="word-wrap: break-word"><%=wording.text.at(0..200)+"..."%> </p>
				          <%= button_to 'Detalhes', wording_path(wording), method: :get, class:'btn btn-default' %>
				    	</div>
					</div>
				</div>
		        
	      	<%end%>
		<%end%>
	</div>
</div>

app/views/wordings/new.html.erb
<div class="container">
	 <%=simple_form_for :wording, url: wordings_path do |f| %> 
	 	 <% if @wording.errors.any? %>
         	<div  class="alert alert-danger">
            	<% @wording.errors.full_messages.each do |r| %>
	           		<p><%= r %></p>
	            	<span></span>
            	<% end %>
         	</div>
         <% end %>
	    <div class="form-group row">
		    <label for="inputEmail3" class="col-sm-2 form-control-label">Titulo</label>
		    <div class="col-sm-10">
		      <%= f.input_field :title, placeholder:'Titulo', class: "form-control"%>
		    </div>
	  	</div>
		  <div class="form-group row">
		    <label for="inputPassword3" class="col-sm-2 form-control-label">Texto</label>
		    <div class="col-sm-10">
		      <%= f.text_area(:text, rows: 8, class:"form-control")%>
		    </div>
		  </div>
	    <%= f.button :submit, value:"Salvar", class: "col-sm-2 btn btn-default btn-lg"%>
	<%end%>	
</div>

app/views/wordings/show.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="row">
				<div class="col-sm-8">
			      <h3><%= @wording.title%></h3>
			    </div>
			    <div class="col-sm-2">
			      	<h2>Nota: <%=@wording.score%></h2>
			    </div>
	  		</div>
	  	</div>
		<div class="panel-body">
		  	<div class="row">
		    <div class="col-sm-12">
		      		<p style="word-wrap: break-word"><%= @wording.text%></p>
		    </div>
		 </div>
		</div>
	</div>

		
		 <% if !(current_user == @wording.user) %>
		 <h2>Novo comentario</h2>
			<%= simple_form_for([@wording, @wording.reviews.build]) do |f| %>
				<% flash.each do |key, value| %>
                            <% if !value.empty? %>
                                <div class="alert alert-danger col-sm-12">
                                    <div><%= value %></div>
                                </div>
                            <% end %>
                        <% end %>
                            
				 <% if @wording.errors.any? %>
         			<div class="alert alert-danger">
            			<% @wording.errors.review.errors.full_messages.each do |r| %>
	           			<p><%= r %></p>
	            		<span></span>
            			<% end %>
         			</div>
         		<% end %>
				<div class="form-group row">
				    <div class="col-sm-2">
				      <%= f.input_field :rate, placeholder:'Nota', class: "form-control", min:'0', max:'1000'%>
				    </div>
				    <div class="col-sm-6">
				      <%= f.input_field :comment, placeholder:'Comentarios', class: "form-control"%>
				    </div>
				    <div class="col-sm-2">
				      <%= f.button :submit, value:"Comentar", class: "btn btn-primary"%>
				    </div>
		  		</div>
			<% end %>
		<% end %>
		<h2>Comentários</h2>
		<div class="form-group row">
			<% @wording.reviews.each do |review| %>
				<% if review.valid? %>
			        <div class="col-md-4">
			        	<div class="panel panel-default">
			        	<% if review.user == current_user %>
				        	<div class="panel-heading">
								<%= link_to [review.wording, review],  method: :delete, data: { confirm: 'Tem certeza?' } do %>
		            					<i class="fa fa-times"></i>
		          					<% end %>

				        	</div>
				        	<% end %>
				        	<div class="panel-body">
						          	
								          <h3><%=review.writer%></h3>
								          <h2><%=review.rate%></h2>
								          <p style="word-wrap: break-word"><%=review.comment%> </p>
					        		
						    </div>
						 </div>
			        </div>
		        <% end %>
			<% end %>
		</div>
</div>